### ISSUE TITLE
Getting error "Dictionary required"

### ISSUE THREAD

**Issue by farzadmf** [voldikss/fzf-floaterm#2]
Hi, I'm trying to use this alongside floaterm.

When I don't have any terminal open, I can safely run `:Floaterms` command, but when I open a terminal (and hide it), when I run `:Floaterms`, I see the following error:
```
Error detected while processing function fzf_floaterm#feed:
line    6:
E715: Dictionary required
```

I must add that, if I press ENTER after this, it will list my terminals, but the error prevents from me calling the function from other plugins or functions that would `abort` if there's an error.

---

Also, I noticed that, when I select the terminal from the list, it's not in `insert` mode and I need to press `i` to interact with the terminal. Is there any way to select the terminal and start interacting with it?

**Comment by Grueslayer** [comment]
The problem is, that *b:floaterm_opts* is not set anymore. The opts are explicitly set in the buffer.

So the name will be the title and is set in *b:floaterm_title*. The next problem is, that if no explicit title is set *b:floaterm_title* will fallback to *g:floaterm_title*.

This is the fix

```diff
diff --git a/autoload/fzf_floaterm.vim b/autoload/fzf_floaterm.vim
index 4fa5883..a2073b0 100644
--- a/autoload/fzf_floaterm.vim
+++ b/autoload/fzf_floaterm.vim
@@ -9,10 +9,11 @@ function! fzf_floaterm#feed()
   let candidates = []
   let bufs = floaterm#buflist#gather()
   for bufnr in bufs
-    let opts = getbufvar(bufnr, 'floaterm_opts')
+    let title = getbufvar(bufnr, 'floaterm_title')
+    let title = (title != get(g:, 'floaterm_title') ? title : 'unnamed')
     let nameparts = [
           \bufnr,
-          \(has_key(opts, 'name') ? opts['name'] : 'unnamed'),
+          \title,
           \getbufinfo(bufnr)[0]['name'],
           \]
     let name = join(nameparts, ' | ')
```

**Comment by voldikss** [comment]
Sorry for the late reply. Will fix this soon.

**Comment by Grueslayer** [comment]
1. you've assigned title but don't used it anywhere
2. as I've written a buffer without an explizit title gives you the global floaterm_title. This contains by default two placeholders.

You need to fix that like I did by comparing the value to the global value and use "unnamed" like before *or* you need to reimplement the static function from

```vim
function! s:make_title(bufnr, text) abort
  if empty(a:text) | return '' | endif
  let buffers = floaterm#buflist#gather()
  let cnt = len(buffers)
  let idx = index(buffers, a:bufnr) + 1
  let title = substitute(a:text, '$1', idx, 'gm')
  let title = substitute(title, '$2', cnt, 'gm')
  return title
endfunction
```
If you don't do you'll get the text with placeholders

```diff
diff --git a/autoload/fzf_floaterm.vim b/autoload/fzf_floaterm.vim
index cd2d38c..046e572 100644
--- a/autoload/fzf_floaterm.vim
+++ b/autoload/fzf_floaterm.vim
@@ -10,7 +10,8 @@ function! fzf_floaterm#feed()
   let bufs = floaterm#buflist#gather()
   for bufnr in bufs
     let title = getbufvar(bufnr, 'floaterm_title')
-    let info = [bufnr, getbufinfo(bufnr)[0]['name']]
+    let title = (title != get(g:, 'floaterm_title') ? title : 'unnamed')
+    let info = [bufnr, title, getbufinfo(bufnr)[0]['name']]
     let line = join(info, ' | ')
     call add(candidates, line)
   endfor
```

**Comment by voldikss** [comment]
@Grueslayer 
Thanks for your reminding.

I think I must have forgotten to delete that line after applying your patch. The title can not indicate any useful meanings in the fuzzy finder window so I've planned to remove it. 

Will delete that line in the next modification.

**Comment by Grueslayer** [comment]
I find it nice, my Terms are mostly opened with "Floaterm --title=Name\ of\ Work" so the Name is really important to fuzzy search for, so the title often is more important than the command line.

**Comment by farzadmf** [comment]
I agree that `title` is super useful when searching

**Comment by voldikss** [comment]
added

**Comment by farzadmf** [comment]
Love it, thank you
